package WebdriverTest;// Generated by Selenium IDE

import org.junit.Assert;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.annotations.*;


import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class LoginTest {
    private WebDriver driver;

    @BeforeTest
    public void setUp() {
        driver = new ChromeDriver();
        driver.get("https://www.skullcandy.com/login.php");
    }

    @AfterTest
    public void tearDown() {
        driver.quit();
    }

    @BeforeMethod
    public void refresh() {
        driver.navigate().refresh();
    }

    @Test
    public void testLogin01() throws InterruptedException {
        driver.findElement(By.id("login_email")).sendKeys("");
        driver.findElement(By.id("login_pass")).sendKeys("Abc12345");
        driver.findElement(By.cssSelector(".form-actions > .button")).click();
        Thread.sleep(1000);
        Assert.assertEquals(driver.findElement(By.className("form-inlineMessage")).getText(), "Please use a valid email address, such as user@example.com.");
    }

    @Test
    public void testLogin02() throws InterruptedException {
        driver.findElement(By.id("login_email")).sendKeys("20021461@vnu.edu.vn");
        driver.findElement(By.id("login_pass")).sendKeys("");
        driver.findElement(By.cssSelector(".form-actions > .button")).click();
        Thread.sleep(1000);
        Assert.assertEquals(driver.findElement(By.className("form-inlineMessage")).getText(), "You must enter a password.");
    }

    @Test
    public void testLogin03() throws InterruptedException {
        String originUrl = driver.getCurrentUrl();
        driver.findElement(By.id("login_email")).sendKeys("20021461@vnu.edu.vn");
        driver.findElement(By.id("login_pass")).sendKeys("123");
        driver.findElement(By.cssSelector(".form-actions > .button")).click();
        Thread.sleep(1000);
        String nextUrl = driver.getCurrentUrl();
        if(originUrl.equals(nextUrl)) {
            Assert.assertEquals(driver.findElement(By.className("alertBox-message")).getText(), "Your email address or password is incorrect. Please try again. If you've forgotten your sign in details, just click the 'Forgot your password?' link below.");
        }
        else Assert.assertEquals(driver.findElement(By.className("alertBox-message")).getText(),"You haven't placed any orders with us. " +
                "When you do, their status will appear on this page.");
    }

    @Test
    public void testLogin04() throws InterruptedException {
        driver.findElement(By.id("login_email")).sendKeys("");
        driver.findElement(By.id("login_pass")).sendKeys("");
        driver.findElement(By.cssSelector(".form-actions > .button")).click();
        Thread.sleep(1000);
        List<WebElement> message = driver.findElements(By.className("form-inlineMessage"));
        //List<WebElement> messages = driver.findElements(By.className("form-inlineMessage"));
        String mes = "";
        for (WebElement i : message) {
            mes += i.getText();
            mes += " ";
        }
        mes = mes.substring(0, mes.length() - 1);
        Assert.assertEquals(mes,
                "Please use a valid email address, such as user@example.com. You must enter a password.");
    }

    @Test
    public void testLogin05() throws InterruptedException {
        String originUrl = driver.getCurrentUrl();
        driver.findElement(By.id("login_email")).sendKeys("20021461@vnu.edu.vn");
        driver.findElement(By.id("login_pass")).sendKeys("Abc12345");
        driver.findElement(By.cssSelector(".form-actions > .button")).click();
        Thread.sleep(1000);
        String nextUrl = driver.getCurrentUrl();
        if(originUrl.equals(nextUrl)) {
            Assert.assertEquals(driver.findElement(By.className("alertBox-message")).getText(), "Your email address or password is incorrect. Please try again. If you've forgotten your sign in details, just click the 'Forgot your password?' link below.");
        }
        else Assert.assertEquals(driver.findElement(By.className("alertBox-message")).getText(),"You haven't placed any orders with us. " +
                "When you do, their status will appear on this page.");
    }
}
